# Generated by Django 2.2.6 on 2019-10-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
                ('reason', models.TextField()),
                ('checkedIn', models.BooleanField(default=False)),
                ('staff', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
