# Generated by Django 2.2.6 on 2019-11-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='PID',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='staff',
            field=models.CharField(max_length=150),
        ),
    ]
