# Generated by Django 2.2.6 on 2020-01-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20191114_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='staff',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='timeOut',
            field=models.TimeField(blank=True),
        ),
    ]
