# Generated by Django 3.1.1 on 2020-09-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20200916_1410'),
        ('checkin', '0005_checkin_haspid'),
    ]

    operations = [
    ]
