# Generated by Django 3.1.1 on 2021-01-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_merge_20200923_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='firstTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkin',
            name='heard',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
