# Generated by Django 3.1.1 on 2021-01-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_auto_20210125_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='heard',
            new_name='heard_through',
        ),
    ]
