image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

variables:
REVIEW_APP_NAME: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"

stages:
    - review
    - production

start_review:
    stage: review
    script:
        - echo "$REVIEW_APP_NAME " $REVIEW_APP_NAME
        - >- 
        curl -n -X POST https://api.heroku.com/apps 
        -d '{
        "name": "'"$REVIEW_APP_NAME"'",
        "region": "us"
        }' 
        -H "Content-Type: application/json" 
        -H "Accept: application/vnd.heroku+json; version=3"
        -H "Authorization: Bearer $HEROKU_API_KEY"
        - dpl --provider=heroku --app=$REVIEW_APP_NAME --api-key=$HEROKU_API_KEY
    environment:
        name: review/$CI_COMMIT_REF_NAME
        url: https://$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA.herokuapp.com
        on_stop: stop_review
    only:
        - branches
    except:
        - master

stop_review:
    stage: review
    script:
        - echo "environment is being stopped!"
        - >-
        curl
        -n
        -X DELETE https://api.heroku.com/apps/$REVIEW_APP_NAME \
        -H "Content-Type: application/json"
        -H "Accept: application/vnd.heroku+json; version=3"
        -H "Authorization: Bearer $HEROKU_API_KEY"
    when: manual
    environment:
        name: review/$CI_COMMIT_REF_NAME
        action: stop
    only:
        - branches
    except:
        - master

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master
        